name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create SSH directory
        run: mkdir -p $HOME/.ssh

      - name: Set Permissions
        run: |
          chmod 700 $HOME/.ssh
          touch $HOME/.ssh/known_hosts
          chmod 644 $HOME/.ssh/known_hosts

      - name: Check and add host key
        run: |
          ssh-keygen -R ec2-3-130-94-241.us-east-2.compute.amazonaws.com
          ssh-keyscan -H ec2-3-130-94-241.us-east-2.compute.amazonaws.com >> $HOME/.ssh/known_hosts

      - name: Install SSH Key
        run: |
          touch $HOME/.ssh/github-actions
          echo "$PRIVATE_KEY" > $HOME/.ssh/github-actions
          chmod 600 $HOME/.ssh/github-actions

      - name: Identify and terminate processes on port 8080
        run: |
          cat $HOME/.ssh/github-actions
          ssh -i $HOME/.ssh/github-actions ec2-user@ec2-3-130-94-241.us-east-2.compute.amazonaws.com "sudo fuser -k 8080/tcp" 2>&1 | tee ssh_output.txt

      - name: Show SSH Command Output
        run: cat ssh_output.txt

      - name: Deploy to EC2
        run: |
          scp -i $HOME/.ssh/github-actions -r ./build/* ec2-user@ec2-3-130-94-241.us-east-2.compute.amazonaws.com:/home/ec2-user/pokemonDeploy

      - name: Execute JAR file
        run: |
          ssh -i $HOME/.ssh/github-actions ec2-user@ec2-3-130-94-241.us-east-2.compute.amazonaws.com "nohup sudo java -jar /home/ec2-user/pokemonDeploy/libs/pokemonYosh-0.0.1-SNAPSHOT.jar > output.log 2>&1 &"

    env:
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_POKEMON }}
