name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create SSH directory
        run: mkdir -p $HOME/.ssh

      - name: Set Permissions
        run: |
          chmod 700 $HOME/.ssh

      - name: Check and add host key
        run: |
          ssh-keyscan -H ec2-3-130-94-241.us-east-2.compute.amazonaws.com >> $HOME/.ssh/known_hosts  

    env:
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
